declare module 'react-native-global-props';
declare module 'react-navigation-transitions';
declare module 'react-native-vector-icons/AntDesign';
declare module 'react-native-wechat';
declare module 'leancloud-installation';
declare module 'react-native-message-bar';
declare module '*.json'
declare module 'dva-model-extend'
declare module 'react-native-tab-view'
declare module 'react-native-camera-kit'
declare module 'react-native-actionsheet'
declare module 'react-native-dialog-input'
declare module 'react-native-emoji-selector'
declare module 'react-native-shadow'
declare module 'react-native-lightbox'
declare module 'react-native-hyperlink'
declare module 'react-native-plugin-zhugeio'
declare module 'react-native-scrollable-tab-view'
declare module 'react-immutable-render-mixin'
declare module 'react-native-scrollable-mixin'
declare module 'react-native-invertible-scroll-view'
declare module 'react-native-rn-cacheimage'
declare module 'rn-snackbar'
declare module 'react-native-update-app'